name: hello-world
on: [push]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: action/checkout@v2

    - name: print text from file index
      run: echo "Hello World!"
