name: test2

on:
  push: 
    branches: 
      - main

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Run Test1
      run: |
        output=$(node dist/Test1.js
